const FETCH_TODOS = "FETCH_TODOS";
const CREATE_TODO = "CREATE_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const DELETE_TODO = "DELETE_TODO";
const FETCH_UPDATE_TODOS = "FETCH_UPDATE_TODOS";

export const TYPE_TODOS = {
  FETCH_TODOS,
  CREATE_TODO,
  UPDATE_TODO,
  DELETE_TODO,
  FETCH_UPDATE_TODOS,
};
